# Generated by Django 5.1.6 on 2025-02-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cliente_clientes_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
