# Generated by Django 5.1.4 on 2025-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='username',
            field=models.CharField(default='usuario_default', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_usuario',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
