# Generated by Django 5.1.4 on 2025-02-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuarios_username_alter_usuarios_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
    ]
