# Generated by Django 5.1.4 on 2025-03-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_usuarios_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_producto',
            field=models.IntegerField(default=int, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
