# Generated by Django 5.1.4 on 2025-03-06 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_producto_id_producto_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='compras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
