# Generated by Django 5.1.4 on 2025-04-15 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_venta_usuario_detalleventa_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='venta',
        ),
    ]
